on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build tensorsat"
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools numpy scipy cotengra kahypar matplotlib pytest
    - name: Build
      run: pip install -e .
    - name: Tests
      run: pytest
